name: linux.yml
on:
  workflow_call:

concurrency:
  group: "${{ github.ref }}-linux"
  cancel-in-progress: true

jobs:
  linux:
    runs-on:
      - ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Install Ninja
        run: sudo apt-get install ninja-build
      - name: Set up sccache
        uses: hendrikmuhs/ccache-action@main
        with:
          key: ${{ github.job }}
          max-size: 1000M
          variant: sccache
      - name: Set up GTest
        uses: Bacondish2023/setup-googletest@v1
        with:
          tag: v1.15.0
      - name: Configure CMake and build
        run: ${{ github.workspace }}/scripts/build_release.sh run_tests
      - name: Run tests
        run: ${{ github.workspace }}/scripts/run_tests.sh

#      - uses: actions/upload-artifact@v4
#        if: success()
#        with:
#          name: "linux-artifacts"
#          retention-days: 28
#          path: |-
#            build/release/bin/libutils
