name: linux.yml
on:
  workflow_call:

concurrency:
  group: "${{ github.ref }}-linux"
  cancel-in-progress: true

jobs:
  linux:
    runs-on:
      - ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Install Ninja
        run: sudo apt-get install ninja-build
      - name: Configure CMake and build
        run: ${{ github.workspace }}/scripts/build_release.sh run_tests
      - name: Run tests
        run: ${{ github.workspace }}/scripts/run_tests.sh

